param(
  [string]$BackupDirectory = $env:BACKUP_DIR
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($BackupDirectory)) {
  throw "Set BACKUP_DIR to a protected directory outside the repository."
}
if ([string]::IsNullOrWhiteSpace($env:BACKUP_S3_BUCKET)) {
  throw "Set BACKUP_S3_BUCKET so scheduled backups are uploaded to private cloud storage."
}
if ([string]::IsNullOrWhiteSpace($env:BACKUP_REMOVE_LOCAL_AFTER_UPLOAD)) {
  # The scheduled workflow keeps the archive only until the cloud upload has
  # been verified. This removes a temporary local copy, never MongoDB data.
  $env:BACKUP_REMOVE_LOCAL_AFTER_UPLOAD = "true"
}

$env:BACKUP_DIR = [System.IO.Path]::GetFullPath($BackupDirectory)
# A restore drill may have set BACKUP_FILE in the interactive shell. Scheduled
# backups must always upload the archive generated by this run instead.
Remove-Item Env:BACKUP_FILE -ErrorAction SilentlyContinue
$repositoryBackend = Split-Path -Parent $PSScriptRoot
Push-Location $repositoryBackend
try {
  npm run backup:mongo
  if ($LASTEXITCODE -ne 0) { throw "MongoDB backup failed with exit code $LASTEXITCODE." }
  npm run backup:upload
  if ($LASTEXITCODE -ne 0) { throw "Cloud backup upload failed with exit code $LASTEXITCODE." }
} finally {
  Pop-Location
}
